version: '3'
services:
  pms-slave:
    network_mode: "host"
    privileged: true
    build: ./
    image: 'docker.astar.moe/pms-slave:latest'
    restart: always
    volumes:
      - './config.toml:/app/config.toml:z'
      - './log4rs.yaml:/app/log4rs.yaml:z'
      - './langs:/app/langs:z'
      - './log:/app/log:z'
    depends_on:
      - redis
  redis:
    image: 'redis:alpine'
    restart: always
    command: redis-server