version: "3"

services:
  pms-slave:
    network_mode: "host"
    privileged: true
    build: ./
    restart: always
    volumes:
      - ./langs:/app/langs
      - ./config.toml:/app/config.toml
      - ./log:/app/log