uuid = "ad9d152c-abbd-4dd2-b484-5825b6a7e4bb"
name = "C++ 20 for Checker"
version = "C++ Standard 20"
exec_cmd = "{file}"
compile_exec = "g++"
compile_args = "-O2 -Wall -lm -static -std=c++20 {infile} -o {outfile} -I /usr/share/testlib"
entry_source = "checker.cpp"
add_mem_limit = 0
add_time_limit = 0