pub const SLEEP_TIME: u64 = 5; // in secs
pub const ISOLATE: &'static str = "isolate";
pub const LOG_FILE_NAME: &'static str = "main.log";
pub const STDIN_FILE_NAME: &'static str = "stdin.in";
pub const STDOUT_FILE_NAME: &'static str = "stdout.out";
pub const STDOUT_ORIGIN_FILE_NAME: &'static str = "stdout_origin.out";
pub const BINARY_NAME: &'static str = "main";
pub const CHECKER_NAME: &'static str = "checker";
pub const CHECKER_TIME_LIMIT: f64 = 5.0;
pub const CHECKER_MEM_LIMIT: u64 = 1048576;
pub const CONVERT_TO_MILLISECS: f64 = 1000.0;
pub const CONVERT_TO_SECONDS: f64 = 0.001;
pub const CHECK_ALIVE_TIME: u64 = 5; // in secs
pub const LOG_CONFIG_FILE: &'static str = "log4rs.yaml";