pub const SLEEP_TIME: u64 = 5; // in secs
pub const ISOLATE: &'static str = "isolate";
pub const BASH: &'static str = "/bin/bash";
pub const LOG_FILE_NAME: &'static str = "main.log";
pub const STDIN_FILE_NAME: &'static str = "input.txt";
pub const STDOUT_FILE_NAME: &'static str = "output.txt";
pub const STDOUT_ORIGIN_FILE_NAME: &'static str = "diff_output.txt";
pub const RESULT_FILE_NAME: &'static str = "result.xml";
pub const BINARY_NAME: &'static str = "main";
pub const CHECKER_NAME: &'static str = "checker";
pub const MANAGER_NAME: &'static str = "manager";
pub const EXEC_SH: &'static str = "exec.sh";
pub const EXEC_MAN_SH: &'static str = "exec_man.sh";
pub const RUN_JUDGE_SH: &'static str = "run.judge.sh";
pub const CHECKER_SH: &'static str = "checker.sh";
pub const GRADERS_PATH: &'static str = "graders/";
pub const LANGUAGES_PATH: &'static str = "langs/";
pub const MAKE: &'static str = "make";
pub const MAKE_ARGS: &'static str = "-j{threads}";
pub const CHECKER_TIME_LIMIT: f64 = 5.0;
pub const CHECKER_MEM_LIMIT: u64 = 1048576;
pub const CONVERT_TO_MILLISECS: f64 = 1000.0;
pub const CONVERT_TO_SECONDS: f64 = 0.001;
pub const CHECK_ALIVE_TIME: u64 = 5; // in secs
pub const LOG_CONFIG_FILE: &'static str = "log4rs.yaml";
